# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ps.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ps.proto\x12\x02ps\"0\n\x0ePublishRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\"\n\x0fPublishResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"!\n\x10SubscribeRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"5\n\x11SubscribeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t2v\n\x02ps\x12\x34\n\x07publish\x12\x12.ps.PublishRequest\x1a\x13.ps.PublishResponse\"\x00\x12:\n\tsubscribe\x12\x14.ps.SubscribeRequest\x1a\x15.ps.SubscribeResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ps_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PUBLISHREQUEST._serialized_start=16
  _PUBLISHREQUEST._serialized_end=64
  _PUBLISHRESPONSE._serialized_start=66
  _PUBLISHRESPONSE._serialized_end=100
  _SUBSCRIBEREQUEST._serialized_start=102
  _SUBSCRIBEREQUEST._serialized_end=135
  _SUBSCRIBERESPONSE._serialized_start=137
  _SUBSCRIBERESPONSE._serialized_end=190
  _PS._serialized_start=192
  _PS._serialized_end=310
# @@protoc_insertion_point(module_scope)
